### ISSUE TITLE
Disable outbound notifications 

### ISSUE THREAD

**Issue by nagpai** [woocommerce/migrator-cli#4]
#### Description

WooCommerce usually has email notifications enabled by default within `Settings > Email`. Whenever we do an import,  the site attempts to send out email notifications: 

* New order notification to the site owner for each imported order
* New account notification to each customer on their email address 

While it is a great idea for the site admin to disable all email notifications manually, as a double check it is better to make sure that these notifications are disabled before the migration starts. 

I am not sure at this moment, what is the best way to do it. A couple of ideas that struck me: 

1. Unset the `to` ( recipient email address ) using filters [similar to these](https://wordpress.stackexchange.com/a/302193), in the plugin activation script.
2. Use WooCommerce hooks, [mentioned here](https://woocommerce.com/document/unhookremove-woocommerce-emails/), to unhook sending of emails for standard WooCommerce notifications. This will however not stop any custom notifications added by extensions - eg. Woo Subscriptions, Back in stock notifications, etc. 
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/migrator-cli/pull/5
- [ ] https://github.com/woocommerce/migrator-cli/pull/6
```

**Comment by Ninodevo** [comment]
We can use a plugin like [Disable Emails](https://wordpress.org/plugins/disable-emails/), this will disable all emails until the import is completed and later we can remove the plugin in addition to that we can use the [WP Mail Logging](https://wordpress.org/plugins/wp-mail-logging/) plugin if we need to see what emails are being sent. This should be first tested with a few random imports with random emails.

**Comment by nagpai** [comment]
@Ninodevo , Thanks! I will test these options. However, with a view of future usage, will it be helpful to have the notifications disabled with the plugin's activation script? If yes, then it would be good to know what method would be better to efficiently block notifications.  

I will test later if hooking an empty array on [this filter](https://woocommerce.github.io/code-reference/files/woocommerce-includes-class-wc-emails.html#source-view.80)  do the job. WDYT?

**Comment by Ninodevo** [comment]
Sorry, I thought that we were commenting on a project thread not on the Migration CLI repository, I didn't check. I think unhooking the emails as the Disable Emails plugin does it is the way to go because that way we can prevent sending emails from all of the plugins while the migration is ongoing.

**Comment by leonardola** [comment]
I think adding a flag to the commands to stop sending emails makes sense. By default I would make it not send emails and only send them when that flag is set to false. It also makes sense to do the same with randomizing the emails and customer data.

This way we would prevent people from installing this plugin not fully reading the documentation and having undesired side effects.
